apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ${{ values.appName }}
  description: ${{ values.description }}
spec:
  type: team
  profile:
    displayName: ${{ values.displayName }}
  children: []