name: Angular CD

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          docker build -t ghcr.io/my-org/angular-app:${{ github.sha }} .
          docker push ghcr.io/my-org/angular-app:${{ github.sha }}