name: NodeJS CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ '${{ github.actor }}' }}
          password: ${{ '${{ secrets.GITHUB_TOKEN }}' }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/udhayakiran-stack/${{ '${{ github.event.repository.name }}' }}:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/

      - name: Restart Deployment
        run: |
          kubectl rollout restart deployment/${{ '${{ github.event.repository.name }}' }}

      - name: Wait for Rollout
        run: |
          kubectl rollout status deployment/${{ '${{ github.event.repository.name }}' }}