apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: ${{ values.appName  }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: udhayakiran-stack/${{ values.appName  }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: ${{ values.owner }}